/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,4],$V1=[1,5],$V2=[1,6],$V3=[1,9],$V4=[1,14],$V5=[1,12],$V6=[1,13],$V7=[1,16],$V8=[1,15],$V9=[1,5,7,8,9,12,16,17,18,19,22,23,28,30],$Va=[20,31],$Vb=[7,8,9,12,16,17,18,19,22,28],$Vc=[12,30];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"BODY":3,"OBJECT":4,"EOF":5,"STRING":6,"NUMBER":7,"REFERENCE":8,"BOOLEAN":9,"ARRAY":10,"DICTIONARY":11,"NAME":12,"INDIRECT_OBJECT":13,"STREAM":14,"objects":15,"[":16,"]":17,"HEXSTRING":18,"OPENPARENS":19,"CLOSEPARENS":20,"chars":21,"INDIRECT_OBJECT_IDENTIFIER":22,"END_INDIRECT_OBJECT":23,"STREAM_HEADER":24,"START_STREAM":25,"STREAM_BUFFER":26,"END_STREAM":27,"<<":28,"keyvaluepairs":29,">>":30,"CHAR":31,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"NUMBER",8:"REFERENCE",9:"BOOLEAN",12:"NAME",16:"[",17:"]",18:"HEXSTRING",19:"OPENPARENS",20:"CLOSEPARENS",22:"INDIRECT_OBJECT_IDENTIFIER",23:"END_INDIRECT_OBJECT",25:"START_STREAM",26:"STREAM_BUFFER",27:"END_STREAM",28:"<<",30:">>",31:"CHAR"},
productions_: [0,[3,2],[3,2],[4,1],[4,1],[4,1],[4,1],[4,1],[4,1],[4,1],[4,1],[4,1],[15,1],[15,2],[10,3],[10,2],[6,1],[6,2],[6,3],[13,3],[24,2],[14,3],[11,3],[29,2],[29,3],[21,1],[21,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: case 2:
 return $$[$0-1] 
break;
case 12: case 25:
 this.$ = [$$[$0]] 
break;
case 13: case 26:
 this.$ = $$[$0-1]; $$[$0-1].push($$[$0]) 
break;
case 14:
 this.$ = $$[$0-1]; 
break;
case 15:
 this.$ = []; 
break;
case 17:
 this.$ = "" 
break;
case 18:
 this.$ = $$[$0-1].join("") 
break;
case 19:

        this.$ = {
          object_number: $$[$0-2].object_number,
          generation_number: $$[$0-2].generation_number,
          value: $$[$0-1],
        }
      
break;
case 20:

        // pretty ugly hack right here
        yy.lexer.stream_length = $$[$0-1].Length;
      
break;
case 21:

        this.$ = { dictionary: $$[$0-2], buffer: $$[$0-1] }
      
break;
case 22:
 this.$ = $$[$0-1] 
break;
case 23:
 this.$ = {}; this.$[$$[$0-1]] = $$[$0]; 
break;
case 24:
 this.$ = $$[$0-2]; $$[$0-2][$$[$0-1]] = $$[$0]; 
break;
}
},
table: [{3:1,4:2,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,18:$V5,19:$V6,22:$V7,24:17,28:$V8},{1:[3]},{4:19,5:[1,18],6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,18:$V5,19:$V6,22:$V7,24:17,28:$V8},o($V9,[2,3]),o($V9,[2,4]),o($V9,[2,5]),o($V9,[2,6]),o($V9,[2,7]),o($V9,[2,8],{25:[1,20]}),o($V9,[2,9]),o($V9,[2,10]),o($V9,[2,11]),o($V9,[2,16]),{20:[1,21],21:22,31:[1,23]},{4:26,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,15:24,16:$V4,17:[1,25],18:$V5,19:$V6,22:$V7,24:17,28:$V8},{12:[1,28],29:27},{4:29,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,18:$V5,19:$V6,22:$V7,24:17,28:$V8},{26:[1,30]},{1:[2,1]},{1:[2,2]},{26:[2,20]},o($V9,[2,17]),{20:[1,31],31:[1,32]},o($Va,[2,25]),{4:34,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,17:[1,33],18:$V5,19:$V6,22:$V7,24:17,28:$V8},o($V9,[2,15]),o($Vb,[2,12]),{12:[1,36],30:[1,35]},{4:37,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,18:$V5,19:$V6,22:$V7,24:17,28:$V8},{23:[1,38]},{27:[1,39]},o($V9,[2,18]),o($Va,[2,26]),o($V9,[2,14]),o($Vb,[2,13]),o([1,5,7,8,9,12,16,17,18,19,22,23,25,28,30],[2,22]),{4:40,6:3,7:$V0,8:$V1,9:$V2,10:7,11:8,12:$V3,13:10,14:11,16:$V4,18:$V5,19:$V6,22:$V7,24:17,28:$V8},o($Vc,[2,23]),o($V9,[2,19]),o($V9,[2,21]),o($Vc,[2,24])],
defaultActions: {18:[2,1],19:[2,2],20:[2,20]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}